# Environment & GPU Check


In [2]:
!nvidia-smi

Tue Jun  7 16:51:33 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    39W / 300W |   4539MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [8]:
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_properties(0))

1
Tesla V100-SXM2-16GB
_CudaDeviceProperties(name='Tesla V100-SXM2-16GB', major=7, minor=0, total_memory=16160MB, multi_processor_count=80)


<b>Note: If we want to use GPU use ".cuda()" otherwise for CPU ".cpu()"<b>

In [10]:
import torch
torch.__version__

'1.12.0.dev20220309+cu113'

In [11]:
import numpy as np 

In [12]:
arr = [1,2,3,4,5]
arr = np.array(arr)

In [13]:
type(arr)

numpy.ndarray

## Convert Numpy To Pytorch Tensors

In [22]:
tensors=torch.tensor(arr)
tensors

tensor([1, 2, 3, 4, 5])

In [23]:
# it is using CPU 
tensors.device

device(type='cpu')

In [24]:
# For GPU
tensors = tensors.cuda()
tensors

tensor([1, 2, 3, 4, 5], device='cuda:0')

In [25]:
tensors.device

device(type='cuda', index=0)

In [26]:
tensors[2]

tensor(3, device='cuda:0')

## Use CPU

In [43]:
##zeros and ones
zero_var_cpu = torch.zeros(2,3,dtype=torch.float64)

In [44]:
zero_var_cpu.device

device(type='cpu')

In [45]:
zero_var_cpu

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

## Use GPU

In [39]:
##zeros and ones
zero_var_gpu = torch.zeros(2,3,dtype=torch.float64).cuda()

In [40]:
zero_var_gpu.device

device(type='cuda', index=0)

In [41]:
zero_var_gpu

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', dtype=torch.float64)

## Arithmetic Operation

In [46]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [47]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [48]:
c=torch.zeros(3)

In [50]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [51]:
c

tensor([ 7.,  9., 11.])

In [52]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [53]:
### tensor[7,9,15]
torch.add(a,b).sum()

tensor(27.)

## Dot Products and Mult Operations

In [54]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [55]:
x.mul(y)

tensor([12., 20., 30.])

In [56]:
### 3*4+5*4+6*5
x.dot(y)

tensor(62.)

In [57]:
###### MAtrix Multiplication
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [58]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [59]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [60]:
x@y

tensor([[55., 53.],
        [90., 92.]])